### PR TITLE
ENH: Bump elastix version to 2022-12-07

### PR DESCRIPTION
**Pull request by N-Dekker**
Including:

pull request https://github.com/SuperElastix/elastix/pull/770
commit https://github.com/SuperElastix/elastix/commit/c0262ba1c713c0a462ada841573e3c452508da3b
"ENH: Add CMake options to not install artifacts", by Matt McCormick (@thewtex)

pull request https://github.com/SuperElastix/elastix/pull/767
"ElastixRegistrationMethod transform objects", adding:

 - ElastixRegistrationMethod::GetCombinationTransform()
 - TransformixFilter::SetCombinationTransform(transform)
 - ElastixRegistrationMethod::GetNumberOfTransforms()
 - ElastixRegistrationMethod::GetNthTransform(n)
 - ElastixRegistrationMethod::ConvertToItkTransform(transform)

pull request https://github.com/SuperElastix/elastix/pull/755
commit https://github.com/SuperElastix/elastix/commit/7fe8ed9b1131e79da7b441827dce0d4abaf64544
"ENH: Add TransformixFilter SpatialJacobian, DeterminantOfSpatialJacobian"

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
I see some errors at the CI from Notebook tests / Run notebooks on treebeard (pull_request) saying:
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> voila 0.4.0 requires nbclient<0.8,>=0.4.0, but you have nbclient 0.3.1 which is incompatible.
> nbconvert 7.2.6 requires nbclient>=0.5.0, but you have nbclient 0.3.1 which is incompatible.

> examples/ITK_UnitTestExample3_BsplineRegistration.ipynb 
> ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

Any suggestion how to fix these?

**Comment by N-Dekker** [comment]
The CI didn't run!

**Comment by thewtex** [comment]
@N-Dekker can this PR be marked Ready for review? That may enable CI.

**Comment by thewtex** [comment]
Lazy CI :-(

Let's merge and get a build going. I will rebase #186

**Pull request merged**
