### PR TITLE
PERF: Remove OpenMP specific CMake code

### PR DESCRIPTION
**Pull request by N-Dekker**
- Following pull request https://github.com/SuperElastix/elastix/pull/1188 "Remove OpenMP based code, ELASTIX_USE_OPENMP option and OpenMP compiler flags"

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
- Interesting... the CI only did build-test-wasm, no other platforms! Looks like pull request #297 commit f1ec2a72705f7dfcaac7cfca97107672a18f6a54 (two weeks ago) already skipped the other platforms. @thewtex Matt, do you possibly have a clue?

**Comment by thewtex** [comment]
@N-Dekker Hmm, seems to have invalid syntax:

  https://github.com/InsightSoftwareConsortium/ITKElastix/pull/301

**Review by thewtex — APPROVED** [review]
Nice!

**Review by N-Dekker — COMMENTED** [review]
Thanks to you both for your approval 👍 Looks good to me as well 😃

**Pull request merged**
