### PR TITLE
ENH: Bump for ITK v5.4rc02

### PR DESCRIPTION
**Pull request by tbirdso**
Succeeds https://github.com/InsightSoftwareConsortium/ITKElastix/pull/256 to bump ITKElastix for ITK v5.4rc02.

See https://github.com/InsightSoftwareConsortium/ITKElastix/pull/256#issue-1957495100 for discussion of relevant fixes between ITK v5.4rc01 and v5.4rc02.

Updates CI and bumps `itk-elastix` to 0.19.1.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Looks good, assuming it works (not segfaults).

**Comment by tbirdso** [comment]
> Looks good, assuming it works (not segfaults).

Agreed. ITKElastix notebook tests were [previously able to detect segfaults](https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/6615805594/job/17973806062), we should verify that they run successfully here.

**Comment by tbirdso** [comment]
It looks like some notebooks ran registration successfully and the notebooks that did fail were not due to segfaults, which is promising. I will push an update to resolve ITKElastix notebook requirements.

**Comment by tbirdso** [comment]
On further review it looks like a resolution may lie in `ITKRemoteModuleBuildTestPackageAction` where the binder `requirements.txt` is not getting picked up correctly. I am in favor of moving forward with this merge and documenting the regression in CI so that we can move forward with releasing v5.4rc2 packages. I should be able to follow up with a proper CI fix in the next day or two.

@dzenanz Do you approve of that plan?

**Comment by dzenanz** [comment]
If the local testing shows that #258 is fixed, that plan sounds reasonable.

**Comment by tbirdso** [comment]
> If the local testing shows that #258 is fixed, that plan sounds reasonable.

Sounds good. I will do more local testing with the build artifacts to confirm before moving forward.

**Comment by tbirdso** [comment]
Confirmed that I am able to reproduce the original segfault issue with `itk==v5.4rc02,itk-elastix==0.19.0` on Windows and no longer see the segfault issue with `itk==v5.4rc02,itk-elastix==0.19.1` (build artifact). The GroupwiseRegistration notebook test also passes now with this build update. Will move forward with merge/tag/release and revisit test failures soon.

**Pull request merged**
