### PR TITLE
ENH: Bump Python package version to 0.18

### PR DESCRIPTION
**Pull request by thewtex**
Include initial transform improvements.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
Please note that the added `ElastixRegistrationMethod::SetExternalInitialTransform` is very new, so it might still have some flaws. Use with care  😃

**Review by tbirdso — APPROVED** [review]

**Comment by thewtex** [comment]
@N-Dekker yes, I make a note in the release notes that it is available for initial experimental testing. :-) Thanks!

**Comment by N-Dekker** [comment]
I'm preparing another extension to elastix, which `TransformixFilter::SetExternalTransform` which would allow specifying any arbitrary ITK transform to be used by transformix. So it's basically complementary to `ElastixRegistrationMethod::SetExternalInitialTransform` Wonder if this should still be included with ITKElastix 0.18. Otherwise, it's also fine to me to have it in 0.19.

**Comment by dzenanz** [comment]
The ability to supply ITK transform and get it out of `ElastixRegistrationMethod` reduces the need for transformix. So I don't think there is any hurry for that functionality.

**Comment by N-Dekker** [comment]
> The ability to supply ITK transform and get it out of `ElastixRegistrationMethod`

Honestly I did not yet add a `GetExternalInitialTransform()` member function to ElastixRegistrationMethod.  Is any hurry for that one, `GetExternalInitialTransform()`? Obviously, it's pretty trivial to write (unlike SetExternalInitialTransform).

**Comment by dzenanz** [comment]
By "get ITK transform out of ElastixRegistrationMethod" I meant this:
```py
comb_transform = elastix_object.GetCombinationTransform()
itk_transform = elastix_object.ConvertToItkTransform(comb_transform)
```

**Comment by tbirdso** [comment]
If there are no objections I will go ahead and merge this shortly.

**Comment by N-Dekker** [comment]
> By "get ITK transform out of ElastixRegistrationMethod" I meant this:
> 
> ```python
> comb_transform = elastix_object.GetCombinationTransform()
> itk_transform = elastix_object.ConvertToItkTransform(comb_transform)
> ```

Sorry @dzenanz `ConvertToItkTransform` does not yet support converting a combination transform that contains an "external" ITK transform. To be continued...!

**Pull request merged**
