### PR TITLE
ENH: Build with 4D elastix support

### PR DESCRIPTION
**Pull request by ViktorvdValk**
Elastix also needed a flag to support 4D floats, which is set in this PR.
However running a 4D registration now, results in ITK giving a MemoryAllocationError, while there's 100gb free space on my drive for a 4D registration of 4 100x100x100 images. This should be enough right?
Any suggestions for a workaround?

### CODE REVIEW

**Comment by dzenanz** [comment]
Free disk size does not play a role in memory allocation (unless you have automatically-increasing swap file). You should look at free memory. Also, are images 100^3, 100^4, 1000^3?

**Review by thewtex — APPROVED** [review]

**Comment by ViktorvdValk** [comment]
I tried to register 4 images of 100x100x100 pixels so 100^3 in a groupwise registration, this involves calling itkelastix/elastix with a 4x100x100x100 pixel image as both fixed and moving image.

**Comment by stefanklein** [comment]
How much RAM do you have available for this process?
Stefan

**Comment by ViktorvdValk** [comment]
16gb, and even registration of 3 10x10x10 pixel images gives the MemoryAllocationError

**Comment by thewtex** [comment]
These changes should now be in `master`.

**Pull request closed without merging**
