### PR TITLE
ENH: Bump elastix version to 2022-10-18 (main branch)

### PR DESCRIPTION
**Pull request by N-Dekker**
Including:

pull request https://github.com/SuperElastix/elastix/pull/745
commit https://github.com/SuperElastix/elastix/commit/a3b081f58ea5c0b39cac211f510ea0fe8aad4958
"BUG: Do not try to load targets file when embedded"
by Matt McCormick (@thewtex)

pull request https://github.com/SuperElastix/elastix/pull/734
commit https://github.com/SuperElastix/elastix/commit/a640e64dc92e12e804a5caa2f634bcad1487d1aa
"BUG: Fix CL_OUT_OF_RESOURCES error"
by Konstantinos Ntatsis (@ntatsisk), with credits to @squll1peter

pull request https://github.com/SuperElastix/elastix/pull/708
commit https://github.com/SuperElastix/elastix/commit/9159c5aac9672ba31f4c88d47de5de69239dacae
"ENH: Support transforming points of Mesh objects by itk::Transformix API"

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
Have the CI scripts been updated for `master` -> `main`?

**Comment by thewtex** [comment]
```
CMake Error at /home/runner/work/ITKElastix/build/_deps/elx-build/ElastixConfig.cmake:36 (include):
  The file

    /home/runner/work/ITKElastix/build/_deps/elx-build/ElastixTargets.cmake

  was generated by the export() command.  It may not be used as the argument
  to the include() command.  Use ALIAS targets instead to refer to targets by
  alternative names.

Call Stack (most recent call first):
  CMakeLists.txt:61 (find_package)

```

https://open.cdash.org/build/8152031/configure

**Comment by N-Dekker** [comment]
> ```
> CMake Error at /home/runner/work/ITKElastix/build/_deps/elx-build/ElastixConfig.cmake:36 (include):
>   The file
> 
>     /home/runner/work/ITKElastix/build/_deps/elx-build/ElastixTargets.cmake
> 
>   was generated by the export() command.  It may not be used as the argument
>   to the include() command.  Use ALIAS targets instead to refer to targets by
>   alternative names.
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:61 (find_package)
> ```
> 
> https://open.cdash.org/build/8152031/configure

Thanks Matt. I have to have a closer look, but it might be triggered (accidentally) by elastix pull request https://github.com/SuperElastix/elastix/pull/655 commit https://github.com/SuperElastix/elastix/commit/3b27d01340f37de78918de723412aa4e743a9270  "Install ElastixTargets.cmake file" (26 May, 2022). Especially because the previous ITKElastix elastix version (https://github.com/SuperElastix/elastix/commit/fe4fe158024bf056a21c6ec6429be553d0178ac3) was still from May 6. Maybe I need Bradley's help (@blowekamp).  😃

**Comment by thewtex** [comment]
The targets issue should be addressed by https://github.com/SuperElastix/elastix/pull/745

@N-Dekker after that patch or one like it, we will need to add `ITKMesh`, `ITKRegistrationCommon` to the `DEPENDS` in *itk-module.cmake* here. It looks like there is a MetaIO dependency that crept out of testing that hopefully can be kept in `TEST_DEPENDS`.

**Comment by blowekamp** [comment]
@N-Dekker Sorry I didn't get back to you on this. I spent a little time looking into the configurations and didn't get any where. Glad to see @thewtex has taken up the issue 👍 

Is the `find_package(ITKElastix)` really needed if all the targets are available after the `add_subdiretory`?

**Comment by thewtex** [comment]
> Is the find_package(ITKElastix) really needed if all the targets are available after the add_subdiretory?

`find_package(ITKElastix)` is used to get other elastix configuration options.

**Comment by N-Dekker** [comment]
Indeed, still those errors at https://open.cdash.org/viewBuildError.php?buildid=8222316

> _deps/elx-src/Core/Main/itkTransformixFilter.h:39:10: fatal error: itkMesh.h: No such file or directory

@thewtex You know how to fix them, right? If so, please go ahead! 😃

**Comment by thewtex** [comment]
@N-Dekker :+1: I added the new module depencies in a commit at the tip of your branch.

**Comment by N-Dekker** [comment]
> I added the new module depencies in a commit at the tip of your branch.

@thewtex  Cool! Thanks Matt! Your commit appears to fix the compile errors on my Windows PC. However, on the CI, macos-10.15 still seems unhappy. Any clue?

**Comment by thewtex** [comment]
@N-Dekker we are getting close!

Yes, those look like elastix test failures. Checking the differences between ITKElastix and elastix GitHub Actions, I see:

- os: macos-10.15 vs macos-11
- cmake-build-type: Release vs MinSizeRel

So, maybe a few test PR's against the `elastix` repository to see if these are related?

**Comment by N-Dekker** [comment]
@thewtex Do you think it's OK to merge now? I hope so  😃 (Otherwise we'd have to investigate why exactly those three old elastix unit tests are having such regression failures on MacOS for a few years now. I'm afraid that would take quite some time.)

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
@N-Dekker thanks for investigating! Yes, let's merge! :green_heart: 

With ITK 5.3.0, GitHub CI will move to `macos-12`, so we may want to re-enable the tests, then.

**Comment by N-Dekker** [comment]
@thewtex Cool!

Regarding the disabled tests, I felt somewhat disappointing that our recently added Python based `TransformixTest` (which tests the old transformix.exe, using Python3) did not work either, because it could not find the `itk` module: commit ea81dc5cb36605995e4e75515e522175c1893b63 It does run well on the SuperElastix/elastix GitHub Actions (including macos-11), for example, https://github.com/SuperElastix/elastix/actions/runs/3311593028/jobs/5467225925 for commit https://github.com/SuperElastix/elastix/commit/61e3df5a33d26b51d6a2e3aeccdf1436ab783c83 

I'm interested to hear why the ITKElastix macos CI was not able to find `itk` Python module for the SuperElastix/elastix `TransformixTest`. (Although honestly, it has no priority for now.)

**Pull request merged**
