### PR TITLE
DOC: Convert README to Markdown

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by romangrothausmann** [comment]
Looks great. Did you use a tool for the conversionf from RST to MD?

**Comment by jhlegarreta** [comment]
> Looks great. Did you use a tool for the conversionf from RST to MD?

@romangrothausmann [Pandoc](https://pandoc.org/) may be help for that purpose.

**Comment by romangrothausmann** [comment]
> @romangrothausmann [Pandoc](https://pandoc.org/) may be help for that purpose.

Many thanks @jhlegarreta for that pointer. Not having used pandoc for this before, I had not though of pandoc.

**Comment by thewtex** [comment]
Yes, pandoc is great :-)

**Pull request merged**
