### PR TITLE
ENH: Switch to latest version of SuperElastix/elastix (using ITK 5.1.1)

### PR DESCRIPTION
**Pull request by N-Dekker**

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
LGTM. Let's see CI results.

**Comment by N-Dekker** [comment]
> LGTM. Let's see CI results.

Thanks Dženan. Apparently there's still an OpenCL issue in SuperElastix/elastix to be fixed:

> _deps/elx-src/Common/OpenCL/ITKimprovements/itkOpenCLLogger.h:72:23: error: ‘PriorityLevelType’ has not been declared

https://github.com/InsightSoftwareConsortium/ITKElastix/runs/1086581143#step:4:1976

I'll have a look!

**Comment by N-Dekker** [comment]
@dzenanz @thewtex My pull request still appears to have some link errors. Which seems to be related to the fact that the SuperElastix/elastix project now distinguished between two CMake targets: elastix_exe and elastix_lib (as I committed with https://github.com/SuperElastix/elastix/commit/3944a13d8dcbe9fcc33cf348f25a1d4f59d79cd7 ). When an application wants to link to the elastix _library_, it must now specify "elastix_lib", instead of just "elastix".

Now it appears that "${Elastix-Test_LIBRARIES}" should be adjusted to specify "elastix_lib" instead of just "elastix", for this `CreateTestDriver` call:

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/0194a64021a0ee722a074e246f8699163dac88e5/test/CMakeLists.txt#L7

Can you please tell me how to properly adjust "${Elastix-Test_LIBRARIES}"? I think it must evaluate to "elastix_lib;transformix_lib;ITKMetaIO;ITKTestKernel"

**Comment by dzenanz** [comment]
Since [this](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/0194a64021a0ee722a074e246f8699163dac88e5/CMakeLists.txt#L63) is set, this might be sufficient:
```CMake
list(APPEND Elastix-Test_LIBRARIES elastix_lib transformix_lib)
CreateTestDriver(Elastix "${Elastix-Test_LIBRARIES}" "${ElastixTests}" )
```
I looked around the code, and don't see how `elastix.lib` used to propagate to the executable. So the above suggestion is more of a guess.

**Comment by N-Dekker** [comment]
@dzenanz Thanks for looking into this issue regarding those link errors. I think it is fixed now, by doing `set(Elastix_LIBRARIES elastix_lib transformix_lib)` in the root-level CMakeLists.

I'm currently looking into
> /work/_skbuild/linux-x86_64-3.5/cmake-build/_deps/elx-src/Core/Kernel/elxElastixMain.h:33:10: fatal error: 'itkOpenCLContext.h' file not found
https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58/checks?check_run_id=1096122268#step:4:2894

Please let me know if you have a clue! Note that 'itkOpenCLContext.h' is in Elastix, at https://github.com/SuperElastix/elastix/blob/develop/Common/OpenCL/ITKimprovements/itkOpenCLContext.h

**Comment by dzenanz** [comment]
Clue: `OpenCL/ITKimprovements` needs to be added to include directories, somewhere 😄 

> The above is somewhat of a joke, I am sure you can deduce that yourself. I looked a bit and don't have useful suggestions 😞

**Comment by N-Dekker** [comment]
@dzenanz Thanks but why did you merge already? It was still in draft status, and it still has failures from build-test-cxx (ubuntu-18.04)!

**Comment by dzenanz** [comment]
I accidentally pushed to all repositories instead of pulling from all repositories.

**Comment by dzenanz** [comment]
I was searching for this PR right now!

**Comment by dzenanz** [comment]
I think you will have to create a new PR. Reusing the same branch in your fork is fine. Sorry for this 😢

**Comment by N-Dekker** [comment]
Then what is the current status? Is it merged now? I don't see it being merged at https://github.com/InsightSoftwareConsortium/ITKElastix/commits/master

**Comment by dzenanz** [comment]
I quickly realized my mistake, and put `master` branch to point to the old commit. But it had a side-effect of closing this PR.

**Comment by dzenanz** [comment]
Please reference this PR in the new PR, in order to keep discussion history.

**Comment by N-Dekker** [comment]
> I quickly realized my mistake, and put master branch to point to the old commit. But it had a side-effect of closing this PR.

So it's a GitHub bug that it doesn't allow reopening the PR!  😸

**Pull request merged**
