### PR TITLE
ENH: CI builds against ITK 5.1.0

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@thewtex you may want to compare with changes I needed to make for getting CI to work with ITKPolartransform (Just the last 3 commits) https://github.com/InsightSoftwareConsortium/ITKPolarTransform/pull/15

This also requires changes to:  https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/137

Hans

**Comment by romangrothausmann** [comment]
Looks good, many thanks for all your work on this.
However it is not clear to me why the CI builds here succeed while my manual debug builds still fail even when using ITK-5.1.0 (https://gitlab.com/romangrothausmann/elastix_scripts/-/jobs/530072390) as already reported for ITK-5.1rc03 (https://github.com/InsightSoftwareConsortium/ITKElastix/pull/40#issuecomment-617643475).

**Comment by thewtex** [comment]
The Azure Pipelines builds did not start :-(, so we do not know their status, yet. I am looking into GitHub Actions instead.

This is building with a branch of elastix on my folk. Once I have verified that the build issues are addressed across platforms, I will push them upstream.

**Comment by thewtex** [comment]
CI is not starting, but I am going to merge and see if it start on `master`. Builds succeed locally.

**Pull request merged**
