### PR TITLE
v0.18.1: Upgrade elastix to 2023-09-18, converts external initial transforms

### PR DESCRIPTION
**Pull request by N-Dekker**
Supports passing a transform retrieved by `GetCombinationTransform()` or `GetNthTransform(n)` to `ConvertToItkTransform`, when an _external_ initial transform was specified before running the registration.

Also including various performance improvements.

Including:

  pull request https://github.com/SuperElastix/elastix/pull/946
  commit https://github.com/SuperElastix/elastix/commit/7bcb2b3ec7b59c85ac9f1cf1564cc90285eabb25
  ENH: Write external initial transforms to ITK transform file

  pull request https://github.com/SuperElastix/elastix/pull/949
  commit https://github.com/SuperElastix/elastix/commit/601f4656e912cc1388fbfa4509d531b7ea5c302f
  ENH: `ConvertToItkTransform` should support external initial transform

  pull request https://github.com/SuperElastix/elastix/pull/950
  commit https://github.com/SuperElastix/elastix/commit/7e883bf473e65761db9a185bb943873962e26eaa
  ENH: Add GetInitialTransform() and GetExternalInitialTransform()

  pull request https://github.com/SuperElastix/elastix/pull/959
  commit https://github.com/SuperElastix/elastix/commit/3979978aaf712c3c78cacdf64eb451aff6eb553d
  PERF: Speed up ComputeJacobianTerms access to `vnl_sparse_matrix`

  pull request https://github.com/SuperElastix/elastix/pull/960
  commit https://github.com/SuperElastix/elastix/commit/4d028f73990347066f8223c2f594e8ae9ae333bb
  PERF: Speed up full, grid, sparse mask samplers by a local sampleVector

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Could you also bump version number in `setup.py`? That way we can immediately after merging this.

**Comment by N-Dekker** [comment]
> That way we can tag/release immediately after merging this.

Wouldn't it be sufficient to you to just locally use one of the wheels produced by the CI?

**Comment by dzenanz** [comment]
I want other people to be able to reproduce my work 😄 And having pip-installable package is super-useful for that.

There is a [compile error](https://open.cdash.org/viewBuildError.php?buildid=8993684): `_deps/elx-src/Core/Main/itkElastixRegistrationMethod.hxx:43:10: fatal error: 'itkTransformFileWriter.h' file not found`.

**Comment by N-Dekker** [comment]
> There is a [compile error](https://open.cdash.org/viewBuildError.php?buildid=8993684): `_deps/elx-src/Core/Main/itkElastixRegistrationMethod.hxx:43:10: fatal error: 'itkTransformFileWriter.h' file not found`.

Thanks @dzenanz I'm busy preparing a fix now.

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
@N-Dekker what is meant by "external" here?

**Comment by N-Dekker** [comment]
> what is meant by "external" here?

Thanks for asking, Matt, it's the topic of the following issue:
- https://github.com/SuperElastix/elastix/issues/961

**Review by thewtex — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
