### PR TITLE
ENH: Bump ITK to v5.3rc04.post3 with reusable CI

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Comment by tbirdso** [comment]
Four test failures from a previous run: https://open.cdash.org/viewTest.php?onlyfailed&buildid=8251231

- Three tests which are disabled in `Elastix` repository CI and therefore can assumed to be invalid for CI testing: https://github.com/SuperElastix/elastix/blob/main/.github/workflows/ElastixGitHubActions.yml#L143
- One Python test, but failing in the cxx-only build

We could disable these individually in our CI, but I don't see the value in duplicating Elastix tests in our CI which are already tested in the `Elastix` repo. Is it acceptable to turn off building `Elastix` tests in our CI and run only tests that are specific to `ITKElastix`? @thewtex @dzenanz

**Comment by dzenanz** [comment]
> turn off building Elastix tests in our CI and run only tests that are specific to ITKElastix

This sounds reasonable to me.

**Comment by tbirdso** [comment]
Thanks @dzenanz .

> Is it acceptable to turn off building `Elastix` tests in our CI and run only tests that are specific to `ITKElastix`?

Looking back I see that this was explicitly disabled in https://github.com/InsightSoftwareConsortium/ITKElastix/commit/db8b57680d23d04992663d7458427ef9481cbb2a. I also see that the four tests in question that are failing were disabled in https://github.com/InsightSoftwareConsortium/ITKElastix/commit/90ab7b422cc4d97d43baf72e76a7aeffc897df9e and re-enabled here by default as a casualty of moving to a reusable pipeline.

I will add an issue for those pipelines to optionally exclude tests by name. It would still be nice to have input from @thewtex and maybe @N-Dekker on whether underlying Elastix tests need to be run in ITKElastix CI.

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
TransformixTest probably fails because some required packages have not been installed at the CI, including `itk` itself! https://open.cdash.org/test/851281751 says:
```
Traceback (most recent call last):
  File "/Users/runner/work/ITKElastix/build/_deps/elx-src/Testing/PythonTests/transformix_test.py", line 28, in <module>
    import itk
ModuleNotFoundError: No module named 'itk'
```

However, I think that ITKElastix CI may slip TransformixTest, as it just tests the transformix executable ("transformix.exe").

**Comment by N-Dekker** [comment]
@tbirdso 
> Is it acceptable to turn off building `Elastix` tests in our CI and run only tests that are specific to `ITKElastix`?

That is acceptable to me. The added merit of rerunning the tests from SuperElastix/elastix at InsightSoftwareConsortium/ITKElastix looks quite small to me. But that's just my impression.

**Comment by thewtex** [comment]
I agree with @N-Dekker @dzenanz -- we can skip the elastix tests if they are causing issues and tested in the elastix repository.

Awesome work @tbirdso !

**Comment by tbirdso** [comment]
It sounds like there is a consensus 👍 Since these changes are already passing I will move forward with existing behavior and add an update disabling Elastix tests in a followup PR.

**Comment by tbirdso** [comment]
Fixed commit message. Previous checks fully passed, moving forward with merge.

**Pull request merged**
