### PR TITLE
STYLE: Use ElastixRegistrationMethod+TransformixFilter from elastix repo

### PR DESCRIPTION
**Pull request by N-Dekker**
Use itkElastixRegistrationMethod and itkTransformixFilter (*.h, *.hxx) from the SuperElastix/elastix git repository.

Remove the "include" directory that has these files from the ITKElastix repository.

SuperElastix/elastix appears a better location for these files.

### CODE REVIEW

**Comment by N-Dekker** [comment]
WIP (Work in Progress): This pull request can only (possibly) be merged _after_ a merge of PR https://github.com/SuperElastix/elastix/pull/300 onto SuperElastix/elastix (develop branch)

**Comment by thewtex** [comment]
@N-Dekker awesome! :rocket:

**Comment by N-Dekker** [comment]
@thewtex Thanks for your encouragement, Matt!

FYI, the itkElastixRegistrationMethod and itkTransformixFilter h/hxx files at the current (October 7) elastix develop branch, at 
https://github.com/SuperElastix/elastix/tree/4d9a50f656d05213803a8b6edb7d3a685232deb5/Core/Main are (still) bitwise identical to your original files ( from https://github.com/InsightSoftwareConsortium/ITKElastix/tree/cfebec78103c4224f0ccac93b8440f8e8513cfad/include )

**Comment by N-Dekker** [comment]
FYI I'm still looking into the compile error at https://open.cdash.org/viewBuildError.php?buildid=6806022

> Site:                             GitHubActions
> Build Name:              InsightSoftwareConsortium/ITKElastix-macos-10.15--refs/pull/66/merge
> Build Time:              2020-10-07 19:20:41

> FAILED: test/CMakeFiles/ElastixTestDriver.dir/itkElastixRegistrationMethodTest.cxx.o 
/Applications/Xcode_11.7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DH5_BUILT_AS_DYNAMIC_LIB -DNDEBUG -I_deps/elx-src/Common -I_deps/elx-src/Common/CostFunctions -I_deps/elx-src/Common/ImageSamplers -I_deps/elx-src/Common/LineSearchOptimizers -I_deps/elx-src/Common/ParameterFileParser -I_deps/elx-src/Common/Transforms -I_deps/elx-src/Common/xout -I_deps/elx-src/Common/MevisDicomTiff -I_deps/elx-src/Core -I_deps/elx-src/Core/Install -I_deps/elx-src/Core/Kernel -I_deps/elx-src/Core/ComponentBaseClasses -I_deps/elx-src/Core/Configuration -I_deps/elx-src/Core/Main -I_deps/elx-src/Components/FixedImagePyramids -I_deps/elx-src/Components/ImageSamplers -I_deps/elx-src/Components/Interpolators -I_deps/elx-src/Components/Metrics -I_deps/elx-src/Components/MovingImagePyramids -I_deps/elx-src/Components/Optimizers -I_deps/elx-src/Components/Registrations -I_deps/elx-src/Components/ResampleInterpolators -I_deps/elx-src/Components/Resamplers -I_deps/elx-src/Components/Transforms -I_deps/elx-build -I/.../ITK-build/Modules/ThirdParty/Eigen3/src -I/.../ITK-build/Modules/ThirdParty/KWIML/src -I/.../ITK/Modules/ThirdParty/KWIML/src -I/.../ITK/Modules/ThirdParty/VNL/src/vxl/core -I/.../ITK-build/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/.../ITK-build/Modules/ThirdParty/VNL/src/vxl/vcl -I/.../ITK-build/Modules/ThirdParty/VNL/src/vxl/core -I/.../ITK-build/Modules/Core/Common -I/.../ITK/Modules/Core/Common/include -I/.../ITK-build/Modules/IO/ImageBase -I/.../ITK/Modules/IO/ImageBase/include -I/.../ITK/Modules/Core/ImageAdaptors/include -I/.../ITK-build/Modules/ThirdParty/Netlib -I/.../ITK/Modules/Numerics/Statistics/include -I/.../ITK/Modules/Filtering/ImageFilterBase/include -I/.../ITK/Modules/Core/Transform/include -I/.../ITK/Modules/Core/ImageFunction/include -I/.../ITK/Modules/Filtering/ImageGrid/include -I/.../ITK/Modules/Filtering/ImageSources/include -I/.../ITK/Modules/Filtering/Smoothing/include -I/.../ITK-build/Modules/ThirdParty/ZLIB/src -I/.../ITK/Modules/ThirdParty/ZLIB/src -I/.../ITK-build/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/.../ITK/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/.../ITK/Modules/ThirdParty/DoubleConversion/src -I/.../ITK-build/Modules/ThirdParty/DoubleConversion/src/double-conversion -I/.../ITK/Modules/Core/TestKernel/include -isystem /.../ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -isystem /.../ITK-build/Modules/ThirdParty/KWSys/src -isystem /.../ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -isystem /.../ITK/Modules/ThirdParty/VNL/src/vxl/vcl -isystem /.../ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo -isystem /.../ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl -isystem /.../ITK/Modules/ThirdParty/NIFTI/src/nifti/znzlib -isystem /.../ITK-build/Modules/ThirdParty/NIFTI/src/nifti/znzlib -isystem /.../ITK/Modules/ThirdParty/NIFTI/src/nifti/niftilib -isystem /.../ITK-build/Modules/ThirdParty/NIFTI/src/nifti/niftilib -isystem /.../ITK-build/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src -isystem /.../ITK/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src -isystem /.../ITK-build/Modules/ThirdParty/HDF5/src/itkhdf5/src -isystem /.../ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src -O3 -DNDEBUG -isysroot /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIE -std=gnu++11 -MD -MT test/CMakeFiles/ElastixTestDriver.dir/itkElastixRegistrationMethodTest.cxx.o -MF test/CMakeFiles/ElastixTestDriver.dir/itkElastixRegistrationMethodTest.cxx.o.d -o test/CMakeFiles/ElastixTestDriver.dir/itkElastixRegistrationMethodTest.cxx.o -c /.../ITKElastix/test/itkElastixRegistrationMethodTest.cxx
In file included from test/itkElastixRegistrationMethodTest.cxx:19:
In file included from _deps/elx-src/Core/Main/itkElastixRegistrationMethod.h:40:
In file included from _deps/elx-src/Core/Kernel/elxElastixMain.h:24:

> _deps/elx-src/Core/Kernel/elxElastixBase.h:39:10: fatal error: 'itkCostFunction.h' file not found

**Comment by N-Dekker** [comment]
@thewtex Now that this PR has passed the CI successfully, is it OK to you to have it merged?

**Review by thewtex — APPROVED** [review]

**Pull request merged**
