### PR TITLE
ENH: Add `ConvertToITKTransform` example

### PR DESCRIPTION
**Pull request by tbirdso**
Adds a Jupyter Notebook example demonstrating how to convert Elastix registration transform results into standard ITK transform format.

### CODE REVIEW

**Comment by dzenanz** [comment]
```py
comb_transform = registration_method.GetCombinationTransform()
itk_composite_transform = registration_method.ConvertToItkTransform(comb_transform)
```
ReviewNB messed up formatting.

**Comment by N-Dekker** [comment]
Thanks for this PR @tbirdso!

ConvertToItkTransform does indeed support converting a "single" transform (as returned by `GetNthTransform`) as well as a "combination transform" (returned by `GetCombinationTransform()`). It converts a combination transform to an ITK `CompositeTransform` (although it will only do so when the elastix combination transform did use composition, rather than addition, to combine the transforms).

**Comment by tbirdso** [comment]
> You need to convert the resulting thing into an ITK transform, like this:

Thanks @dzenanz , this is the step I was missing. I will revise the notebook to prefer this approach 👍

**Comment by dzenanz** [comment]
Since you already did the work, you could leave the current thing as an alternative approach.

**Comment by tbirdso** [comment]
To avoid confusion between two approaches I've opted to remove the previous approach manually composing an `itk.CompositeTransform` from individual stages and instead use the expected type information for validation.

**Comment by thewtex** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/InsightSoftwareConsortium/ITKElastix/pull/243/discussion/#comment-1696053432'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by thewtex — APPROVED** [review]
Love this!! :book: :heart:

**Pull request merged**
