### PR TITLE
BUG: Change voila tornado settings specification

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
The comment in the notebook doesn't work for me:

```text
(pyE) C:\Dev\ITKRemotes\ITKElastix>python -m voila --Voila.tornado_settings '{\"websocket_max_message_size\":838860800}' --theme=dark ./examples/ITK_Registration_App.ipynb
[Voila] CRITICAL | Bad config encountered during initialization: The 'tornado_settings' trait of a Voila instance expected a dict, not the list ['\'{"websocket_max_message_size":838860800}\''].
```

**Comment by dzenanz** [comment]
I have voila version: 0.2.4

**Comment by thewtex** [comment]
> The comment in the notebook doesn't work for me:

This is likely a Windows shell quoting issue.

This might work, `"--Voila.tornado_settings={\"websocket_max_message_size\":838860800}"`

**Comment by dzenanz** [comment]
> This might work, `"--Voila.tornado_settings={\"websocket_max_message_size\":838860800}"`

It works. I force-pushed to update the comment with the command.

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
