### PR TITLE
WIP: ENH: CI builds against ITK 6.0 Alpha 1

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@N-Dekker we are getting:

```
src/Common/itkScaledSingleValuedNonLinearOptimizer.h:21,
398
                 from /work/build/cp39-cp39-linux_x86_64/_deps/elx-src/Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.h:22,
399
                 from /work/build/cp39-cp39-linux_x86_64/_deps/elx-src/Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.cxx:19:
400
/work/ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:1008:3: error: expected ‘;’ before ‘virtual’
401
 1008 |   virtual type Get##name() const { return this->m_##name; } \
402
      |   ^~~~~~~
403
/work/build/cp39-cp39-linux_x86_64/_deps/elx-src/Components/Optimizers/ConjugateGradient/itkGenericConjugateGradientOptimizer.h:123:5: note: in expansion of macro ‘itkGetConstMacro’
404
  123 |     itkGetConstMacro(ValueTolerance, double);
 ```
 
 Does that ring a bell?

**Comment by N-Dekker** [comment]
> `/work/ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:1008:3: error: expected ‘;’ before ‘virtual’`
> Does that ring a bell?

Yes it does! ITK now requires a semicolon at the end of a `itkSetMacro` call. It does so from ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4706 commit https://github.com/InsightSoftwareConsortium/ITK/commit/55e23393e1d2c2e71d919d33459201fcee364655 (which is after ITK 5.4.0)

SuperElastix/elastix did not always have a semicolon with each such macro call. This was fixed by the following 3 commits:
- https://github.com/SuperElastix/elastix/commit/9554422f0b8a6fe422ca7ed3c2f56a3a7522a386 (Aug 30) 
- https://github.com/SuperElastix/elastix/commit/c41fdd6a4ceb460348e25b8bb0861a536c97dd5e (Aug 31) 
- https://github.com/SuperElastix/elastix/commit/0852e7a4db5281f1be67f88163e66d350e1590c7 (Oct 1)

I would suggest to just upgrade ITKElastix to the latest main revision of SuperElastix/elastix, https://github.com/SuperElastix/elastix/commit/f928159ed6c25c4aec01adebf2c4d1211c3dc006

**Comment by thewtex** [comment]
@N-Dekker excellent, thank you for the information!

I pushed a bump to the latest elastix `main`.

**Comment by thewtex** [comment]
Superceded by https://github.com/InsightSoftwareConsortium/ITKElastix/pull/310

**Pull request closed without merging**
